name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Build Web
        run: npm run build || echo "No build script"

      - name: Add Android
        run: npx cap add android || echo "Android exists"

      - name: Sync
        run: npx cap sync

      - name: Build APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: renris-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
